terms:
  - id: Graphite
    term: Graphite
  - id: Ink
    term: Ink
  - id: Marker pen
    term: Marker pen
  - id: Photographic print - Color
    term: Photographic print - Color
  - id: Photographic Print - Black and White
    term: Photographic Print - Black and White
  - id: Printed ink
    term: Printed ink
  - id: Watercolors
    term: Watercolors
