terms:
  - id: Articles
    term: Articles
  - id: Clippings
    term: Clippings
  - id: Correspondence
    term: Correspondence
  - id: Documents
    term: Documents
  - id: Drawings - Axonometric
    term: Drawings - Axonometric
  - id: Drawings - Concept
    term: Drawings - Concept
  - id: Drawings - Details
    term: Drawings - Details
  - id: Drawings - Elevation
    term: Drawings - Elevation
  - id: Drawings - Floor plans
    term: Drawings - Floor plans
  - id: Drawings - Interior
    term: Drawings - Interior
  - id: Drawings - Perspective
    term: Drawings - Perspective
  - id: Drawings - Presentation
    term: Drawings - Presentation
  - id: Drawings - Section
    term: Drawings - Section
  - id: Drawings - Site plans
    term: Drawings - Site plans
  - id: Notebooks
    term: Notebooks
  - id: Photographs
    term: Photographs
  - id: Postcards
    term: Postcards
  - id: Sketchbooks
    term: Sketchbooks
  - id: Sketches
    term: Sketches
  - id: Travel sketches
    term: Travel sketches
