development:
  user: <%= Rails.application.secrets[:fedora][:user] %>
  password: <%= Rails.application.secrets[:fedora][:password] %>
  url: <%= Rails.application.secrets[:fedora][:url] %>
  base_path: <%= Rails.application.secrets[:fedora][:base_path] %>
test:
  user: <%= Rails.application.secrets[:fedora][:user] %>
  password: <%= Rails.application.secrets[:fedora][:password] %>
  url: <%= ENV['TRAVIS'] ? 'http://localhost:8986/rest' : Rails.application.secrets[:fedora][:url] %>
  base_path: <%= Rails.application.secrets[:fedora][:base_path] %>
production:
  user: <%= Rails.application.secrets[:fedora][:user] %>
  password: <%= Rails.application.secrets[:fedora][:password] %>
  url: <%= Rails.application.secrets[:fedora][:url] %>
  base_path: <%= Rails.application.secrets[:fedora][:base_path] %>
