development:
  host: <%= Rails.application.secrets[:redis][:host] %>
  port: <%= Rails.application.secrets[:redis][:port] %>
test:
  host: <%= Rails.application.secrets[:redis][:host] %>
  port: <%= Rails.application.secrets[:redis][:port] %>
production:
  host: <%= Rails.application.secrets[:redis][:host] %>
  port: <%= Rails.application.secrets[:redis][:port] %>
