development:
  archivist:
    - archivist1@example.com
    - whunter@vt.edu
    - virjtt03@vt.edu

test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  archivist:
    - specref@vt.edu
    - whunter@vt.edu
    - virjtt03@vt.edu
    - kdweeks@vt.edu
    - aserra@vt.edu
    - samw@vt.edu
    - rfitz12@vt.edu
    - jss3838@vt.edu
