# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  validates :rights, presence: { message: 'Your collection must have a right.' }
  validates :identifier, presence: { message: 'Your collection must have an identifier.' }
  validates :rights_holder, presence: { message: 'Your collection must have a rights holder.' }

  # Add members using the members association.
  def add_members(new_member_ids)
    return if new_member_ids.nil? || new_member_ids.empty?
    items = ActiveFedora::Base.find(new_member_ids)
    items.each do |item|
      item.rights = self.rights
      item.bibliographic_citation = self.bibliographic_citation
      item.save
    end
    members << items
  end

  def export_csv
    headers = ["Collection Identifier", "Item Identifier", "Title", "Circa",
               "Start Date", "End Data", "Description", "Subject", "Type",
               "Medium", "Format", "Creator", "Source", "Location of Originals",
               "Language", "Coverage", "Tags", "Related URL", "Contributor",
               "Rights", "Rights Holder", "Bibliographic Citation"]
    CSV.generate(headers: true) do |csv|
      csv << headers
      member_objects.each do |item|
        csv << item.csv_values
      end
    end
  end
end
